import { CONFIG, isPreview, mediaUrl } from './config.js';
import { initAnalytics, readAttribution, track } from './analytics.js';
import { fetchStore, postPayload } from './api.js';
import { cartCount, cartSubtotal, loadCart, saveCart } from './cart.js';
import { createOrderPayload, reconcileCart, validateCheckout } from './checkout-core.js';
import { initCartDrawer } from './cart-drawer.js';
import { formatMoney } from './products-ui.js';
import { loadStore, normalizeStore } from './store.js';
import { mountSiteShell } from './ui.js';
import { escapeHtml } from './utils.js';

let store = null;
let cart = [];
let submitting = false;
let completed = false;
const REQUEST_KEY = isPreview() ? 'tochka_hruskotu_checkout_request_v3_preview' : 'tochka_hruskotu_checkout_request_v3';
const $ = (selector) => document.querySelector(selector);

function requestId(){let id=sessionStorage.getItem(REQUEST_KEY);if(!id){id=globalThis.crypto?.randomUUID?.()||`REQ-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;sessionStorage.setItem(REQUEST_KEY,id);}return id;}
function clearRequestId(){sessionStorage.removeItem(REQUEST_KEY);}
function deviceType(){return window.innerWidth<=760?'mobile':window.innerWidth<=1100?'tablet':'desktop';}
function threshold(){return Number(store?.settings?.freeDeliveryFrom||store?.settings?.freeDeliveryFromAmount||store?.settings?.freeDeliveryThreshold||CONFIG.business.freeDeliveryFrom||0);}
function hasSecretItems(){return cart.some((item)=>item.messageMode==='secret');}

function renderSummary(){const node=$('[data-checkout-items]');const total=$('[data-checkout-total]');const count=$('[data-checkout-count]');if(!node||!total)return;node.innerHTML=cart.length?cart.map((item)=>`<article class="checkout-line"><img src="${escapeHtml(mediaUrl(item.photo))}" alt=""><div><strong>${escapeHtml(item.secretTitle||item.name||item.code)}</strong>${item.secretTitle?`<small>${escapeHtml(item.name||item.code)}</small>`:''}${item.variantValue?`<small>${escapeHtml(item.variantValue)}</small>`:''}${item.sauces?.length?`<small>Соус: ${escapeHtml(item.sauces.join(', '))}</small>`:''}<span>${item.qty} × ${formatMoney(item.price)}</span></div><b>${formatMoney(item.qty*item.price)}</b></article>`).join(''):'<div class="empty-state">Кошик порожній. Поверніться до каталогу й додайте товари.</div>';const subtotal=cartSubtotal(cart);total.textContent=formatMoney(subtotal);const itemsCount=cartCount(cart);if(count)count.textContent=String(itemsCount);document.querySelectorAll('[data-cart-count]').forEach((n)=>{n.textContent=String(itemsCount);});renderFreeDelivery(subtotal);const secretBox=$('[data-secret-checkout]');if(secretBox)secretBox.hidden=!hasSecretItems();}
function renderFreeDelivery(subtotal){const node=$('[data-free-delivery-progress]');if(!node)return;const min=threshold();if(!min){node.textContent='';return;}if(subtotal>=min){node.textContent='Безкоштовна доставка активована для відділення, поштомату або погодженої передачі. Кур’єр оплачується окремо.';node.classList.add('is-ready');}else{node.textContent=`До безкоштовної доставки залишилося ${formatMoney(min-subtotal)}.`;node.classList.remove('is-ready');}}
function fillDeliveryMethods(){const select=$('[name="deliveryCode"]');const items=(store?.deliveryMethods||[]).filter((item)=>item.active!==false).sort((a,b)=>Number(a.order||0)-Number(b.order||0));select.innerHTML='<option value="">Оберіть спосіб отримання</option>'+items.map((item)=>`<option value="${escapeHtml(item.code)}">${escapeHtml(item.name||item.code)}</option>`).join('');}
function allPayments(){return (store?.paymentMethods||[]).filter((item)=>item.active!==false);}
function fillPayments(){const select=$('[name="paymentCode"]');if(!select)return;const deliveryCode=$('[name="deliveryCode"]')?.value||'';const payments=allPayments();let bank=payments.find((p)=>p.code==='IBAN_FOP')||payments.find((p)=>p.code==='CARD_FOP');const options=[];if(bank)options.push(bank);if(deliveryCode==='PICKUP'){const cash=payments.find((p)=>p.code==='CASH_PICKUP');if(cash)options.push(cash);}if(!options.length)options.push(...payments);const previous=select.value;select.innerHTML='<option value="">Оберіть спосіб оплати</option>'+options.map((payment)=>`<option value="${escapeHtml(payment.code)}">${payment.code==='IBAN_FOP'||payment.code==='CARD_FOP'?'Оплата на розрахунковий рахунок ФОП':escapeHtml(payment.name||payment.code)}</option>`).join('');if(options.some((p)=>p.code===previous))select.value=previous;else if(options.length===1)select.value=options[0].code;updatePaymentNote();}
function selectedDelivery(){const code=$('[name="deliveryCode"]')?.value;return (store?.deliveryMethods||[]).find((item)=>item.code===code)||null;}
function updateDeliveryFields(){const method=selectedDelivery();const regionWrap=$('[data-region-field]');const cityWrap=$('[data-city-field]');const branchWrap=$('[data-branch-field]');regionWrap.hidden=!method?.requireRegion;cityWrap.hidden=!method?.requireCity;branchWrap.hidden=!method?.requireBranch;const branchLabel=$('[data-branch-label]');if(branchLabel)branchLabel.textContent=method?.branchLabel||'Дані доставки';const branch=$('[name="branch"]');if(branch)branch.placeholder=method?.branchPlaceholder||'';if(!method?.requireRegion)$('[name="region"]').value='';if(!method?.requireCity)$('[name="city"]').value='';if(!method?.requireBranch)$('[name="branch"]').value='';const note=$('[data-delivery-note]');if(note)note.textContent=method?.note||'';fillPayments();renderMiniSummary();}
function updatePaymentNote(){const node=$('[data-payment-note]');if(!node)return;const code=$('[name="paymentCode"]')?.value||'';if(code==='IBAN_FOP'||code==='CARD_FOP')node.textContent='Після оформлення ми перевіримо замовлення й надішлемо реквізити для оплати.';else if(code==='CASH_PICKUP')node.textContent='Оплата готівкою під час самовивозу.';else node.textContent='';renderMiniSummary();}
function updateRecipientFields(){const other=$('[name="recipientMode"]:checked')?.value==='other';$('[data-recipient-fields]').hidden=!other;renderMiniSummary();}
function updateSecretHint(){const mode=$('[name="signatureMode"]:checked')?.value||'named';$('[data-secret-hint]').hidden=mode!=='hint';if(mode!=='hint')$('[name="hint"]').value='';renderMiniSummary();}
function updatePostcard(){const checked=Boolean($('[name="postcardRequested"]')?.checked);const wrap=$('[data-postcard-text]');if(wrap)wrap.hidden=!checked;if(!checked&&$('[name="postcardText"]'))$('[name="postcardText"]').value='';renderMiniSummary();}
function readForm(){const form=$('[data-checkout-form]');const deliveryCode=form.elements.deliveryCode.value;const isPickup=deliveryCode==='PICKUP';return{fullName:form.elements.fullName.value.trim(),phone:form.elements.phone.value.trim(),email:form.elements.email.value.trim(),recipientMode:form.elements.recipientMode.value,recipientName:form.elements.recipientName.value.trim(),recipientPhone:form.elements.recipientPhone.value.trim(),region:isPickup?CONFIG.business.pickup.region:form.elements.region.value.trim(),city:isPickup?CONFIG.business.pickup.locality:form.elements.city.value.trim(),deliveryCode,branch:form.elements.branch.value.trim(),paymentCode:form.elements.paymentCode.value,desiredDate:form.elements.desiredDate.value,isGift:form.elements.isGift.checked,hasCertificate:form.elements.hasCertificate.checked,certificateCode:form.elements.certificateCode.value.trim(),signatureMode:hasSecretItems()?form.elements.signatureMode.value:'named',hint:hasSecretItems()?form.elements.hint.value.trim():'',postcardRequested:hasSecretItems()?Boolean(form.elements.postcardRequested?.checked):false,postcardText:hasSecretItems()?(form.elements.postcardText?.value||'').trim():'',comment:form.elements.comment.value.trim(),termsAccepted:form.elements.termsAccepted.checked};}
function renderMiniSummary(){const node=$('[data-checkout-mini-summary]');if(!node)return;const delivery=selectedDelivery();const payment=allPayments().find((p)=>p.code===$('[name="paymentCode"]')?.value);const other=$('[name="recipientMode"]:checked')?.value==='other';const parts=[];if(other)parts.push(`<span><b>Отримувач:</b> ${escapeHtml($('[name="recipientName"]')?.value||'вкажіть дані')}</span>`);if(delivery)parts.push(`<span><b>Доставка:</b> ${escapeHtml(delivery.name||delivery.code)}</span>`);if(payment)parts.push(`<span><b>Оплата:</b> ${payment.code==='IBAN_FOP'||payment.code==='CARD_FOP'?'розрахунковий рахунок ФОП':escapeHtml(payment.name||payment.code)}</span>`);if(hasSecretItems()){const mode=$('[name="signatureMode"]:checked')?.value||'named';parts.push(`<span><b>Послання:</b> ${mode==='anonymous'?'анонімно':mode==='hint'?'анонімно з підказкою':'від вашого імені'}</span>`);if($('[name="postcardRequested"]')?.checked)parts.push('<span><b>Листівка:</b> додати</span>');}node.innerHTML=parts.join('');}
function setStatus(message,type=''){const node=$('[data-checkout-status]');node.textContent=message;node.className=`checkout-status${type?` is-${type}`:''}`;}
function renderSuccess(result){$('[data-checkout-form-wrap]').hidden=true;$('[data-checkout-success]').hidden=false;$('[data-success-number]').textContent=result.orderNumber||result.number||result.orderId||'прийнято';}
async function submit(event){event.preventDefault();if(submitting||completed)return;const formData=readForm();const method=selectedDelivery();const validation=validateCheckout({form:formData,cart,deliveryMethod:method});if(validation){setStatus(validation,'error');return;}if(isPreview()&&!CONFIG.checkout.previewSubmitEnabled){setStatus('Це тестова версія: оформлення можна пройти до кінця, але справжнє замовлення поки не відправиться.','info');return;}submitting=true;const button=$('[data-submit-order]');button.disabled=true;button.textContent='Ще мить…';setStatus('Перевіряємо, чи все в замовленні актуальне.','info');try{const freshStore=normalizeStore(await fetchStore());const reconciled=reconcileCart(cart,freshStore);if(reconciled.errors.length){cart=reconciled.items;saveCart(cart);renderSummary();throw new Error(reconciled.errors.join(' '));}cart=reconciled.items;saveCart(cart);renderSummary();store=freshStore;const attribution=readAttribution();const payload=createOrderPayload({requestId:requestId(),form:formData,cart,attribution,source:'GitHub Pages — Точка Хрускоту V3',device:deviceType()});button.textContent='Надсилаємо…';setStatus('Замовлення вже майже у нас — ще кілька секунд.','info');const result=await postPayload(payload);completed=true;track('purchase',{transaction_id:result.orderNumber||result.orderId||payload.requestId,currency:'UAH',value:cartSubtotal(cart),items:cart.map((item)=>({item_id:item.code,item_name:item.name,price:item.price,quantity:item.qty,item_variant:item.secretTitle||item.variantValue}))});saveCart([]);clearRequestId();renderSuccess(result);}catch(error){console.error(error);setStatus(error.message||'Щось завадило оформленню. Спробуйте ще раз — кошик нікуди не зник.','error');button.disabled=false;button.textContent='Підтвердити замовлення';}finally{submitting=false;}}
async function boot(){mountSiteShell();initAnalytics();initCartDrawer();cart=loadCart();try{const result=await loadStore();store=result.data;const reconciled=reconcileCart(cart,store);cart=reconciled.items;saveCart(cart);renderSummary();fillDeliveryMethods();updateDeliveryFields();if(reconciled.errors.length)setStatus(reconciled.errors.join(' '),'error');}catch(error){console.error(error);setStatus('Схоже, оформлення на хвилинку замислилося. Оновіть сторінку або поверніться трохи пізніше — кошик збережеться.','error');$('[data-submit-order]').disabled=true;}
$('[name="deliveryCode"]')?.addEventListener('change',()=>{updateDeliveryFields();track('add_shipping_info',{shipping_tier:$('[name="deliveryCode"]').value});});$('[name="paymentCode"]')?.addEventListener('change',()=>{updatePaymentNote();track('add_payment_info',{payment_type:$('[name="paymentCode"]').value});});document.querySelectorAll('[name="recipientMode"]').forEach((node)=>node.addEventListener('change',updateRecipientFields));document.querySelectorAll('[name="signatureMode"]').forEach((node)=>node.addEventListener('change',updateSecretHint));$('[name="postcardRequested"]')?.addEventListener('change',updatePostcard);$('[name="hasCertificate"]')?.addEventListener('change',(event)=>{$('[data-certificate-field]').hidden=!event.target.checked;});$('[data-checkout-form]')?.addEventListener('submit',submit);$('[data-checkout-form]')?.addEventListener('input',renderMiniSummary);window.addEventListener('v3:cart-changed',(event)=>{cart=event.detail?.cart||loadCart();if(store){const reconciled=reconcileCart(cart,store);cart=reconciled.items;}renderSummary();});updateRecipientFields();updateSecretHint();updatePostcard();track('begin_checkout',{currency:'UAH',value:cartSubtotal(cart),items:cart.map((item)=>({item_id:item.code,item_name:item.name,price:item.price,quantity:item.qty}))});}
boot();
